### ISSUE TITLE
UnicodeDecode error in genderComputer.py line 60

### ISSUE THREAD

**Issue by raffaem** [tue-mdse/genderComputer#11]
```
$ python
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from genderComputer import GenderComputer
>>> gc = GenderComputer()
Loaded dictionary from C:\PortablePrograms\genderComputer\nameLists\gender.dict
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\PortablePrograms\genderComputer\genderComputer.py", line 178, in __init__
    self.nameLists[country]['male'], self.nameLists[country]['female'] = loadData(country, self.dataPath, hasHeader=False)
  File "C:\PortablePrograms\genderComputer\genderComputer.py", line 87, in loadData
    males = loadGenderList('Male', country, dataPath, hasHeader)
  File "C:\PortablePrograms\genderComputer\genderComputer.py", line 60, in loadGenderList
    for row in reader:
  File "C:\Users\Raffaele\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 216: character maps to <undefined>
```

**Comment by aserebrenik** [comment]
@bvasiles ?

**Comment by bvasiles** [comment]
Only Python 2.7

**Comment by aserebrenik** [comment]
Thank you @bvasiles !

**Comment by raffaem** [comment]
I did not understand the answer by @bvasiles.

As you can see from the output, I am running Python 3.8.5, not 2.7.

The Exception is raised when I initialize the class, preventing the use of the library altogether.

Is it possible to solve it?

It seems a non-Unicode character in `gender.dict`

Best

**Comment by bvasiles** [comment]
Sorry about the confusing answer. I meant to say that you should run Python 2.7. That's why the exception is raised.

**Comment by raffaem** [comment]
With this PR the library works also with Python 3.8.5 👍
