### ISSUE TITLE
Getting error: argument must me unicode, not str

### ISSUE THREAD

**Issue by iMashiro** [tue-mdse/genderComputer#4]
When I try to gc.resolvegender(name,country) I got an error:
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    gc.resolveGender('Alexei Matrosov', 'Russia')
  File "/home/hyago/Documentos/EASY/SANER2020/GENDER/genderComputer.py", line 557, in resolveGender
    if only_cyrillic_chars(name) or only_greek_chars(name):
  File "/home/hyago/Documentos/EASY/SANER2020/GENDER/nameUtils.py", line 118, in only_cyrillic_chars
    for uchr in unistr if uchr.isalpha())
  File "/home/hyago/Documentos/EASY/SANER2020/GENDER/nameUtils.py", line 118, in <genexpr>
    for uchr in unistr if uchr.isalpha())
  File "/home/hyago/Documentos/EASY/SANER2020/GENDER/nameUtils.py", line 113, in is_cyrillic
    return cyrillic_letters.setdefault(uchr, 'CYRILLIC' in unicodedata.name(uchr))
TypeError: name() argument 1 must be unicode, not str

**Comment by aserebrenik** [comment]
@bvasiles can you please take a look?

**Comment by bvasiles** [comment]
Strange, I didn’t get any notification about this otherwise old issue. Apologies @iMashiro 

The last line in your stack trace explains the cause. The inputs (names) must be utf-8. Also, the code was written in Python 2.7.

Which Python are you using and how are you reading in the inputs?
